// mockData.js
import user1 from "./images/profilepic.png";
import user2 from "./images/user1.png";
import user3 from "./images/Avatar3.png";
import user4 from "./images/Avatar4.png";
import user5 from "./images/Avatar5.png";
import user6 from "./images/Avatar6.png";
import user7 from "./images/Avatar7.png";
import user8 from "./images/Avatar (8).png";
import user9 from "./images/Avatar (9).png";
import user10 from "./images/Dropdown (1).png";

const mockData = {
  users: [
    {
      id: 1,
      employee_id: "#E00123454GH6",
      name: "Alice Johnson",
      email: "alice.johnson@gmail.com",
      role: {
        mainrole: "Software Engineer",
        subrole: "Full time",
      },
      status: "Active",
      Teams: ["Marketing", "Design", "Product"],
      phone: "9876553221",
      city: "Gwenborough",
      zipcode: "92998-3874",
      image: user1,
    },
    {
      id: 2,
      employee_id: "#E002123454GH6",
      name: "Bob Smith",
      email: "bob.smith@gmail.com",
      role: {
        mainrole: "Product Manager",
        subrole: "Full time",
      },
      status: "Active",
      Teams: ["Product", "Marketing"],
      phone: "9876553222",
      city: "Gwenborough",
      zipcode: "92998-3875",
      image: user2,
    },
    {
      id: 3,
      employee_id: "#E00323454GH6",
      name: "Carol Williams",
      email: "carol.williams@gmail.com",
      role: {
        mainrole: "UX Designer",
        subrole: "Part time",
      },
      status: "Inactive",
      Teams: ["Design"],
      phone: "9876553223",
      city: "Howemouth",
      zipcode: "92998-3876",
      image: user3,
    },
    {
      id: 4,
      employee_id: "#E00423454GH6",
      name: "David Brown",
      email: "david.brown@gmail.com",
      role: {
        mainrole: "Backend Engineer",
        subrole: "Full time",
      },
      status: "Active",
      Teams: ["Engineering", "Product"],
      phone: "9876553224",
      city: "Wisokyburgh",
      zipcode: "92998-3877",
      image: user4,
    },
    {
      id: 5,
      employee_id: "#E00523454GH6",
      name: "Eve Johnson",
      email: "eve.johnson@gmail.com",
      role: {
        mainrole: "Data Scientist",
        subrole: "Full time",
      },
      status: "Active",
      Teams: ["Data", "Product"],
      phone: "9876553225",
      city: "South Elvis",
      zipcode: "92998-3878",
      image: user5,
    },
    {
      id: 6,
      employee_id: "#E00623454GH6",
      name: "Frank Lee",
      email: "frank.lee@gmail.com",
      role: {
        mainrole: "Marketing Specialist",
        subrole: "Part time",
      },
      status: "Inactive",
      Teams: ["Marketing"],
      phone: "9876553226",
      city: "New Mallory",
      zipcode: "92998-3879",
      image: user6,
    },
    {
      id: 7,
      employee_id: "#E00723454GH6",
      name: "Grace Green",
      email: "grace.green@gmail.com",
      role: {
        mainrole: "HR Manager",
        subrole: "Full time",
      },
      status: "Active",
      Teams: ["HR"],
      phone: "9876553227",
      city: "Aliyaview",
      zipcode: "92998-3880",
      image: user7,
    },
    {
      id: 8,
      employee_id: "#E00823454GH6",
      name: "Henry White",
      email: "henry.white@gmail.com",
      role: {
        mainrole: "DevOps Engineer",
        subrole: "Full time",
      },
      status: "Active",
      Teams: ["Engineering", "Operations"],
      phone: "9876553228",
      city: "West Minster",
      zipcode: "92998-3881",
      image: user8,
    },
    {
      id: 9,
      employee_id: "#E00923454GH6",
      name: "Ivy Black",
      email: "ivy.black@gmail.com",
      role: {
        mainrole: "Project Manager",
        subrole: "Full time",
      },
      status: "Inactive",
      Teams: ["Product", "Operations"],
      phone: "9876553229",
      city: "Lebsackbury",
      zipcode: "92998-3882",
      image: user9,
    },
    {
      id: 10,
      employee_id: "#E001023454GH6",
      name: "Jack Brown",
      email: "jack.brown@gmail.com",
      role: {
        mainrole: "Security Analyst",
        subrole: "Full time",
      },
      status: "Active",
      Teams: ["Security"],
      phone: "9876553230",
      city: "Roscoeview",
      zipcode: "92998-3883",
      image: user10,
    },
    {
      id: 11,
      employee_id: "#E001123454GH6",
      name: "Kathy Clark",
      email: "kathy.clark@gmail.com",
      role: {
        mainrole: "Content Writer",
        subrole: "Part time",
      },
      status: "Active",
      Teams: ["Content", "Marketing"],
      phone: "9876553231",
      city: "Bartholomebury",
      zipcode: "92998-3884",
      image: user10,
    },
    {
      id: 12,
      employee_id: "#E001223454GH6",
      name: "Leo Martin",
      email: "leo.martin@gmail.com",
      role: {
        mainrole: "Frontend Developer",
        subrole: "Full time",
      },
      status: "Active",
      Teams: ["Engineering", "Design"],
      phone: "9876553232",
      city: "Taylorside",
      zipcode: "92998-3885",
      image: user9,
    },
    {
      id: 13,
      employee_id: "#E001323454GH6",
      name: "Mia Young",
      email: "mia.young@gmail.com",
      role: {
        mainrole: "Quality Analyst",
        subrole: "Full time",
      },
      status: "Inactive",
      Teams: ["Quality Assurance"],
      phone: "9876553233",
      city: "Newhouse",
      zipcode: "92998-3886",
      image: user8,
    },
    {
      id: 14,
      employee_id: "#E001423454GH6",
      name: "Noah Adams",
      email: "noah.adams@gmail.com",
      role: {
        mainrole: "Database Administrator",
        subrole: "Full time",
      },
      status: "Active",
      Teams: ["Data"],
      phone: "9876553234",
      city: "Carrollton",
      zipcode: "92998-3887",
      image: user7,
    },
    {
      id: 15,
      employee_id: "#E001523454GH6",
      name: "Olivia Parker",
      email: "olivia.parker@gmail.com",
      role: {
        mainrole: "Business Analyst",
        subrole: "Full time",
      },
      status: "Active",
      Teams: ["Business"],
      phone: "9876553235",
      city: "Greenborough",
      zipcode: "92998-3888",
      image: user6,
    },
    {
      id: 16,
      employee_id: "#E001623454GH6",
      name: "Paul Wright",
      email: "paul.wright@gmail.com",
      role: {
        mainrole: "System Administrator",
        subrole: "Full time",
      },
      status: "Inactive",
      Teams: ["IT Support"],
      phone: "9876553236",
      city: "Brookfield",
      zipcode: "92998-3889",
      image: user5,
    },
    {
      id: 17,
      employee_id: "#E001723454GH6",
      name: "Quinn Scott",
      email: "quinn.scott@gmail.com",
      role: {
        mainrole: "Network Engineer",
        subrole: "Full time",
      },
      status: "Active",
      Teams: ["Networking"],
      phone: "9876553237",
      city: "Rutherford",
      zipcode: "92998-3890",
      image: user4,
    },
    {
      id: 18,
      employee_id: "#E001823454GH6",
      name: "Rachel Evans",
      email: "rachel.evans@gmail.com",
      role: {
        mainrole: "Sales Executive",
        subrole: "Full time",
      },
      status: "Active",
      Teams: ["Sales"],
      phone: "9876553238",
      city: "Fayetteville",
      zipcode: "92998-3891",
      image: user3,
    },
    {
      id: 19,
      employee_id: "#E001923454GH6",
      name: "Sam Turner",
      email: "sam.turner@gmail.com",
      role: {
        mainrole: "Technical Support",
        subrole: "Full time",
      },
      status: "Inactive",
      Teams: ["Support"],
      phone: "9876553239",
      city: "Kingsland",
      zipcode: "92998-3892",
      image: user2,
    },
    {
      id: 20,
      employee_id: "#E002023454GH6",
      name: "Tina Brooks",
      email: "tina.brooks@gmail.com",
      role: {
        mainrole: "Product Designer",
        subrole: "Full time",
      },
      status: "Active",
      Teams: ["Design", "Product"],
      phone: "9876553240",
      city: "North Hilltop",
      zipcode: "92998-3893",
      image: user1,
    },
    {
      id: 21,
      employee_id: "#E001123454GH6",
      name: "Kathy Clark",
      email: "kathy.clark@gmail.com",
      role: {
        mainrole: "Content Writer",
        subrole: "Part time",
      },
      status: "Active",
      Teams: ["Content", "Marketing"],
      phone: "9876553231",
      city: "Bartholomebury",
      zipcode: "92998-3884",
      image: user10,
    },
    {
      id: 22,
      employee_id: "#E001223454GH6",
      name: "Leo Martin",
      email: "leo.martin@gmail.com",
      role: {
        mainrole: "Frontend Developer",
        subrole: "Full time",
      },
      status: "Active",
      Teams: ["Engineering", "Design"],
      phone: "9876553232",
      city: "Taylorside",
      zipcode: "92998-3885",
      image: user9,
    },
    {
      id: 23,
      employee_id: "#E001323454GH6",
      name: "Mia Young",
      email: "mia.young@gmail.com",
      role: {
        mainrole: "Quality Analyst",
        subrole: "Full time",
      },
      status: "Inactive",
      Teams: ["Quality Assurance"],
      phone: "9876553233",
      city: "Newhouse",
      zipcode: "92998-3886",
      image: user8,
    },
    {
      id: 24,
      employee_id: "#E001423454GH6",
      name: "Noah Adams",
      email: "noah.adams@gmail.com",
      role: {
        mainrole: "Database Administrator",
        subrole: "Full time",
      },
      status: "Active",
      Teams: ["Data"],
      phone: "9876553234",
      city: "Carrollton",
      zipcode: "92998-3887",
      image: user7,
    },
    {
      id: 25,
      employee_id: "#E001523454GH6",
      name: "Olivia Parker",
      email: "olivia.parker@gmail.com",
      role: {
        mainrole: "Business Analyst",
        subrole: "Full time",
      },
      status: "Active",
      Teams: ["Business"],
      phone: "9876553235",
      city: "Greenborough",
      zipcode: "92998-3888",
      image: user6,
    },
    {
      id: 26,
      employee_id: "#E001623454GH6",
      name: "Paul Wright",
      email: "paul.wright@gmail.com",
      role: {
        mainrole: "System Administrator",
        subrole: "Full time",
      },
      status: "Inactive",
      Teams: ["IT Support"],
      phone: "9876553236",
      city: "Brookfield",
      zipcode: "92998-3889",
      image: user5,
    },
    {
      id: 27,
      employee_id: "#E001723454GH6",
      name: "Quinn Scott",
      email: "quinn.scott@gmail.com",
      role: {
        mainrole: "Network Engineer",
        subrole: "Full time",
      },
      status: "Active",
      Teams: ["Networking"],
      phone: "9876553237",
      city: "Rutherford",
      zipcode: "92998-3890",
      image: user4,
    },
  ],
};

export default mockData;
